package com.atguigu.crowd.entity;

import java.io.Serializable;

public class Admin implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.id
     *
     * @mbg.generated Sat Nov 14 11:35:58 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.login_acct
     *
     * @mbg.generated Sat Nov 14 11:35:58 CST 2020
     */
    private String loginAcct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.user_pswd
     *
     * @mbg.generated Sat Nov 14 11:35:58 CST 2020
     */
    private String userPswd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.user_name
     *
     * @mbg.generated Sat Nov 14 11:35:58 CST 2020
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.email
     *
     * @mbg.generated Sat Nov 14 11:35:58 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.create_time
     *
     * @mbg.generated Sat Nov 14 11:35:58 CST 2020
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_admin
     *
     * @mbg.generated Sat Nov 14 11:35:58 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.id
     *
     * @return the value of t_admin.id
     *
     * @mbg.generated Sat Nov 14 11:35:58 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.id
     *
     * @param id the value for t_admin.id
     *
     * @mbg.generated Sat Nov 14 11:35:58 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.login_acct
     *
     * @return the value of t_admin.login_acct
     *
     * @mbg.generated Sat Nov 14 11:35:58 CST 2020
     */
    public String getLoginAcct() {
        return loginAcct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.login_acct
     *
     * @param loginAcct the value for t_admin.login_acct
     *
     * @mbg.generated Sat Nov 14 11:35:58 CST 2020
     */
    public void setLoginAcct(String loginAcct) {
        this.loginAcct = loginAcct == null ? null : loginAcct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.user_pswd
     *
     * @return the value of t_admin.user_pswd
     *
     * @mbg.generated Sat Nov 14 11:35:58 CST 2020
     */
    public String getUserPswd() {
        return userPswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.user_pswd
     *
     * @param userPswd the value for t_admin.user_pswd
     *
     * @mbg.generated Sat Nov 14 11:35:58 CST 2020
     */
    public void setUserPswd(String userPswd) {
        this.userPswd = userPswd == null ? null : userPswd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.user_name
     *
     * @return the value of t_admin.user_name
     *
     * @mbg.generated Sat Nov 14 11:35:58 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.user_name
     *
     * @param userName the value for t_admin.user_name
     *
     * @mbg.generated Sat Nov 14 11:35:58 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.email
     *
     * @return the value of t_admin.email
     *
     * @mbg.generated Sat Nov 14 11:35:58 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.email
     *
     * @param email the value for t_admin.email
     *
     * @mbg.generated Sat Nov 14 11:35:58 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.create_time
     *
     * @return the value of t_admin.create_time
     *
     * @mbg.generated Sat Nov 14 11:35:58 CST 2020
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.create_time
     *
     * @param createTime the value for t_admin.create_time
     *
     * @mbg.generated Sat Nov 14 11:35:58 CST 2020
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbg.generated Sat Nov 14 11:35:58 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", loginAcct=").append(loginAcct);
        sb.append(", userPswd=").append(userPswd);
        sb.append(", userName=").append(userName);
        sb.append(", email=").append(email);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    public Admin(Integer id, String loginAcct, String userPswd, String userName, String email, String createTime) {
        this.id = id;
        this.loginAcct = loginAcct;
        this.userPswd = userPswd;
        this.userName = userName;
        this.email = email;
        this.createTime = createTime;
    }

    public Admin() {
    }


}